from _typeshed import Incomplete

class ObjectNotFoundException(Exception): ...
class AssetAttachFailedException(Exception): ...
class NotAuthorizedException(Exception): ...
class RequestFailedException(Exception): ...
class NoDefaultAppException(Exception): ...
class InvalidHTTPMethodException(Exception): ...
class NoSuchAttributeException(Exception): ...
class PropertyNotSetException(Exception): ...
class InvalidParameterException(Exception): ...

class UniqnameDoesNotExistException(Exception):
    uniqname: Incomplete
    message: Incomplete
    def __init__(self, uniqname: str, message: str = ...) -> None: ...

class MultipleMatchesException(Exception):
    message: Incomplete
    type: Incomplete
    def __init__(self, type: str, message: str = ...) -> None: ...

class InvalidUniqnameException(Exception): ...
